repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        exclude: derex/runner/settings/derex/*

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.0
    hooks:
      - id: isort

  - repo: https://github.com/prettier/prettier
    rev: 2.1.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: docs/html_templates/layout.html
