CASES = [
    {
        "expected_result": 1600260602894815,
        "data": {
            "format": {
                "bit_rate": "123339",
                "duration": "80.678000",
                "filename": "/home/silvio/svn/probostitcher/tests/test-files/videoroom-1234-user-7098320872262523-1600260602068888-video.webm",
                "format_long_name": "Matroska / WebM",
                "format_name": "matroska,webm",
                "nb_programs": 0,
                "nb_streams": 1,
                "probe_score": 100,
                "size": "1243853",
                "start_time": "0.000000",
                "tags": {
                    "COMMENT": '{"t": "v", "c": "vp8", "s": 1600260602068890, "u": 1600260602894815}',
                    "ENCODER": "Lavf58.29.100",
                },
            },
            "streams": [
                {
                    "avg_frame_rate": "10/1",
                    "codec_long_name": "On2 VP8",
                    "codec_name": "vp8",
                    "codec_tag": "0x0000",
                    "codec_tag_string": "[0][0][0][0]",
                    "codec_time_base": "1/10",
                    "codec_type": "video",
                    "coded_height": 300,
                    "coded_width": 480,
                    "display_aspect_ratio": "8:5",
                    "disposition": {
                        "attached_pic": 0,
                        "clean_effects": 0,
                        "comment": 0,
                        "default": 1,
                        "dub": 0,
                        "forced": 0,
                        "hearing_impaired": 0,
                        "karaoke": 0,
                        "lyrics": 0,
                        "original": 0,
                        "timed_thumbnails": 0,
                        "visual_impaired": 0,
                    },
                    "field_order": "progressive",
                    "has_b_frames": 0,
                    "height": 300,
                    "index": 0,
                    "level": -99,
                    "pix_fmt": "yuv420p",
                    "profile": "0",
                    "r_frame_rate": "10/1",
                    "refs": 1,
                    "sample_aspect_ratio": "1:1",
                    "start_pts": 0,
                    "start_time": "0.000000",
                    "tags": {"DURATION": "00:01:20.678000000"},
                    "time_base": "1/1000",
                    "width": 480,
                }
            ],
        },
    }
]
