name: pytest

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install probostitcher
        run: pip install -r requirements.txt -e .
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest
        env:
          CREATE_VIDEO: "True"
          PROBOSTITCHER_REGION: dummy
          PROBOSTITCHER_OUTPUT_BUCKET: dummy
